import Head from "next/head";

// COMPONENTS
import Header from "../components/Header";
import Nav from "../components/Nav";
import Result from "../components/Result";

// UTIL
import request from "../utils/request";

export default function Home({ results }) {
  return (
    <div>
      <Head>
        <title>Hulu clone</title>
        <meta
          name="description"
          content="Hulu 2.0 clone generated by sridhar @MrDarkCoder for learning Next JS + Tailwind CSS via yt"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Nav />

      <Result results={results} />
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;
  const data = await fetch(
    `https://api.themoviedb.org/3${
      request[genre]?.url || request.fetchTrending.url
    }`
  ).then((res) => res.json());
  // console.log(data)

  return {
    props: {
      results: data.results,
    },
  };
}
